//val MRStrings = DMRStrings()
//
//class DMRStrings {
//    val darkTheme: StringResource = MR.strings.darkTheme
//    val lightTheme: StringResource = MR.strings.lightTheme
//    val autoTheme: StringResource = MR.strings.autoTheme
//    val chooseTheme: StringResource = MR.strings.chooseTheme
//    val chooseThemeUnder: StringResource = MR.strings.chooseThemeUnder
//}
//val mguImage = MR.images.MGU
//val passKeyImage = MR.images.Passkey
val MRColors = DMRColors()

class DMRColors{
    //Default
    val defaultLightPrimary: String              = "#0b57d0"
    val defaultLightOnPrimary: String            = "#FFFFFF"
    val defaultLightPrimaryContainer: String     = "#d3e3fd"
    val defaultLightOnPrimaryContainer: String   = "#041e49"
    val defaultLightInversePrimary: String       = "#a8c7fa"
    val defaultLightSecondary: String            = "#00639b"
    val defaultLightOnSecondary: String          = "#FFFFFF"
    val defaultLightSecondaryContainer: String   = "#c2e7ff"
    val defaultLightOnSecondaryContainer: String = "#001d35"
    val defaultLightTertiary: String             = "#93f7bb"
    val defaultLightOnTertiary: String           = "#002110"
    val defaultLightTertiaryContainer: String    = "#c4eed0"
    val defaultLightOnTertiaryContainer: String  = "#072711"
    val defaultLightBackground: String           = "#ffffff"
    val defaultLightOnBackground: String         = "#1f1f1f"
    val defaultLightSurface: String              = "#ffffff" //default light background
    val defaultLightOnSurface: String            = "#1f1f1f" //on Back
    val defaultLightSurfaceVariant: String       = "#e1e3e1"
    val defaultLightOnSurfaceVariant: String     = "#444746"
    val defaultLightSurfaceTint: String          = "#0b57d0" //primary
    val defaultLightInverseSurface: String       = "#303030"
    val defaultLightInverseOnSurface: String     = "#f2f2f2"
    val defaultLightError: String                = "#b3261e"
    val defaultLightOnError: String              = "#FFFFFF"
    val defaultLightErrorContainer: String       = "#FFDAD6"
    val defaultLightOnErrorContainer: String     = "#410002"
    val defaultLightOutline: String              = "#747775"
    val defaultLightOutlineVariant: String       = "#74777550"

    val defaultDarkPrimary:              String = "#a8c7fa" // defaultLightInversePrimary
    val defaultDarkOnPrimary:            String = "#062e6f"
    val defaultDarkPrimaryContainer:     String = "#0842a0"
    val defaultDarkOnPrimaryContainer:   String = "#d3e3fd" // defaultLightPrimaryContainer
    val defaultDarkInversePrimary:       String = "#0b57d0" // defaultLightPrimary
    val defaultDarkSecondary:            String = "#7fcfff"
    val defaultDarkOnSecondary:          String = "#003355"
    val defaultDarkSecondaryContainer:   String = "#004a77"
    val defaultDarkOnSecondaryContainer: String = "#c2e7ff" // defaultLightSecondaryContainer
    val defaultDarkTertiary:             String = "#00531f"
    val defaultDarkOnTertiary:           String = "#a3f6ab"
    val defaultDarkTertiaryContainer:    String = "#0f5223"
    val defaultDarkOnTertiaryContainer:  String = "#c4eed0" // defaultLightTertiaryContainer
    val defaultDarkBackground:           String = "#1f1f1f"
    val defaultDarkOnBackground:         String = "#e3e3e3"
    val defaultDarkSurface:              String = "#1f1f1f" // defaultDarkBackground
    val defaultDarkOnSurface:            String = "#e3e3e3" // defaultDarkOnBackground
    val defaultDarkSurfaceVariant:       String = "#444746"
    val defaultDarkOnSurfaceVariant:     String = "#c4c7c5"
    val defaultDarkSurfaceTint:          String = "#a8c7fa" // defaultDarkPrimary
    val defaultDarkInverseSurface:       String = "#e3e3e3"
    val defaultDarkInverseOnSurface:     String = "#303030"
    val defaultDarkError:                String = "#f2b8b5"
    val defaultDarkOnError:              String = "#601410"
    val defaultDarkErrorContainer:       String = "#7D2B22"
    val defaultDarkOnErrorContainer:     String = "#FFDAD6" // defaultLightErrorContainer
    val defaultDarkOutline:              String = "#8e918f"
    val defaultDarkOutlineVariant:       String = "#8e918f50"



    //GREEN
    val greenLightPrimary:              String = "#386A20"
    val greenLightOnPrimary:            String = "#FFFFFF"
    val greenLightPrimaryContainer:     String = "#B8F397"
    val greenLightOnPrimaryContainer:   String = "#042100"
    val greenLightInversePrimary:       String = "#9CD67D"
    val greenLightSecondary:            String = "#55624C"
    val greenLightOnSecondary:          String = "#FFFFFF"
    val greenLightSecondaryContainer:   String = "#D9E7CB"
    val greenLightOnSecondaryContainer: String = "#131F0D"
    val greenLightTertiary:             String = "#6FF6F8"
    val greenLightOnTertiary:           String = "#002020"
    val greenLightTertiaryContainer:    String = "#BBEBEB"
    val greenLightOnTertiaryContainer:  String = "#002021"
    val greenLightBackground:           String = "#FDFDF6"
    val greenLightOnBackground:         String = "#1A1C18"
    val greenLightSurface:              String = "#FDFDF6" // greenLightBackground
    val greenLightOnSurface:            String = "#1A1C18" // greenLightOnBackground
    val greenLightSurfaceVariant:       String = "#DFE4D6"
    val greenLightOnSurfaceVariant:     String = "#43493E"
    val greenLightSurfaceTint:          String = "#386A20" // greenLightPrimary
    val greenLightInverseSurface:       String = "#2F312C"
    val greenLightInverseOnSurface:     String = "#F1F1EA"
    val greenLightError:                String = "#BA1B1B"
    val greenLightOnError:              String = "#FFFFFF"
    val greenLightErrorContainer:       String = "#FFDAD6"
    val greenLightOnErrorContainer:     String = "#410002"
    val greenLightOutline:              String = "#74796E"
    val greenLightOutlineVariant:       String = "#74796E50"

    val greenDarkPrimary:              String = "#9CD67D" // greenLightInversePrimary
    val greenDarkOnPrimary:            String = "#0C3900"
    val greenDarkPrimaryContainer:     String = "#205107"
    val greenDarkOnPrimaryContainer:   String = "#B8F397" // greenLightPrimaryContainer
    val greenDarkInversePrimary:       String = "#386A20" // greenLightPrimary
    val greenDarkSecondary:            String = "#BDCBB0"
    val greenDarkOnSecondary:          String = "#273420"
    val greenDarkSecondaryContainer:   String = "#3E4A36"
    val greenDarkOnSecondaryContainer: String = "#D9E7CB" // greenLightSecondaryContainer
    val greenDarkTertiary:             String = "#004F50"
    val greenDarkOnTertiary:           String = "#6FF7F7"
    val greenDarkTertiaryContainer:    String = "#1E4E4E"
    val greenDarkOnTertiaryContainer:  String = "#BBEBEB" // greenLightTertiaryContainer
    val greenDarkBackground:           String = "#1A1C18"
    val greenDarkOnBackground:         String = "#E3E3DC"
    val greenDarkSurface:              String = "#1A1C18" // greenDarkBackground
    val greenDarkOnSurface:            String = "#E3E3DC" // greenDarkOnBackground
    val greenDarkSurfaceVariant:       String = "#43493E"
    val greenDarkOnSurfaceVariant:     String = "#C4C8BB"
    val greenDarkSurfaceTint:          String = "#9CD67D" // greenDarkPrimary
    val greenDarkInverseSurface:       String = "#2F312C"
    val greenDarkInverseOnSurface:     String = "#E3E3DC"
    val greenDarkError:                String = "#FFB4A9"
    val greenDarkOnError:              String = "#680003"
    val greenDarkErrorContainer:       String = "#7D2B22"
    val greenDarkOnErrorContainer:     String = "#FFDAD6" // greenLightErrorContainer
    val greenDarkOutline:              String = "#8D9286"
    val greenDarkOutlineVariant:       String = "#8D928650"


    //RED
    val redLightPrimary:              String = "#9c4146"
    val redLightOnPrimary:            String = "#FFFFFF"
    val redLightPrimaryContainer:     String = "#ffdadb"
    val redLightOnPrimaryContainer:   String = "#400008"
    val redLightInversePrimary:       String = "#ffb3b5"
    val redLightSecondary:            String = "#765656"
    val redLightOnSecondary:          String = "#FFFFFF"
    val redLightSecondaryContainer:   String = "#ffdad9"
    val redLightOnSecondaryContainer: String = "#2d1516"
    val redLightTertiary:             String = "#ffdeac"
    val redLightOnTertiary:           String = "#281900"
    val redLightTertiaryContainer:    String = "#ffddaa"
    val redLightOnTertiaryContainer:  String = "#281800"
    val redLightBackground:           String = "#fcfcfc"
    val redLightOnBackground:         String = "#211a1a"
    val redLightSurface:              String = "#fcfcfc" // redLightBackground
    val redLightOnSurface:            String = "#211a1a" // redLightOnBackground
    val redLightSurfaceVariant:       String = "#f4dedd"
    val redLightOnSurfaceVariant:     String = "#534343"
    val redLightSurfaceTint:          String = "#9c4146" // redLightPrimary
    val redLightInverseSurface:       String = "#362f2f"
    val redLightInverseOnSurface:     String = "#fbeeed"
    val redLightError:                String = "#BA1B1B"
    val redLightOnError:              String = "#FFFFFF"
    val redLightErrorContainer:       String = "#FFDAD6"
    val redLightOnErrorContainer:     String = "#410002"
    val redLightOutline:              String = "#857373"
    val redLightOutlineVariant:       String = "#85737350"

    val redDarkPrimary:              String = "#ffb3b5" // redLightInversePrimary
    val redDarkOnPrimary:            String = "#5f121b"
    val redDarkPrimaryContainer:     String = "#7d2a30"
    val redDarkOnPrimaryContainer:   String = "#ffdadb" // redLightPrimaryContainer
    val redDarkInversePrimary:       String = "#9c4146" // redLightPrimary
    val redDarkSecondary:            String = "#e6bcbc"
    val redDarkOnSecondary:          String = "#442929"
    val redDarkSecondaryContainer:   String = "#5c3f3f"
    val redDarkOnSecondaryContainer: String = "#ffdad9" // redLightSecondaryContainer
    val redDarkTertiary:             String = "#614000"
    val redDarkOnTertiary:           String = "#ffddaf"
    val redDarkTertiaryContainer:    String = "#5b4219"
    val redDarkOnTertiaryContainer:  String = "#ffddaa" // redLightTertiaryContainer
    val redDarkBackground:           String = "#211a1a"
    val redDarkOnBackground:         String = "#ede0df"
    val redDarkSurface:              String = "#211a1a" // redDarkBackground
    val redDarkOnSurface:            String = "#ede0df" // redDarkOnBackground
    val redDarkSurfaceVariant:       String = "#534343"
    val redDarkOnSurfaceVariant:     String = "#d7c2c1"
    val redDarkSurfaceTint:          String = "#ffb3b5" // redDarkPrimary
    val redDarkInverseSurface:       String = "#362f2f"
    val redDarkInverseOnSurface:     String = "#fbeeed"
    val redDarkError:                String = "#ffb4a9"
    val redDarkOnError:              String = "#680003"
    val redDarkErrorContainer:       String = "#7D2B22"
    val redDarkOnErrorContainer:     String = "#FFDAD6" // redLightErrorContainer
    val redDarkOutline:              String = "#a08c8c"
    val redDarkOutlineVariant:       String = "#a08c8c50"

    //YELLOW
    val yellowLightPrimary:              String = "#616200"
    val yellowLightOnPrimary:            String = "#FFFFFF"
    val yellowLightPrimaryContainer:     String = "#e8e971"
    val yellowLightOnPrimaryContainer:   String = "#1d1d00"
    val yellowLightInversePrimary:       String = "#cbcc58"
    val yellowLightSecondary:            String = "#606042"
    val yellowLightOnSecondary:          String = "#FFFFFF"
    val yellowLightSecondaryContainer:   String = "#e6e4bf"
    val yellowLightOnSecondaryContainer: String = "#1c1d06"
    val yellowLightTertiary:             String = "#82f8cf"
    val yellowLightOnTertiary:           String = "#002117"
    val yellowLightTertiaryContainer:    String = "#bfedd9"
    val yellowLightOnTertiaryContainer:  String = "#002117"
    val yellowLightBackground:           String = "#fffcf3"
    val yellowLightOnBackground:         String = "#1c1c16"
    val yellowLightSurface:              String = "#fffcf3" // yellowLightBackground
    val yellowLightOnSurface:            String = "#1c1c16" // yellowLightOnBackground
    val yellowLightSurfaceVariant:       String = "#e6e3d1"
    val yellowLightOnSurfaceVariant:     String = "#48473a"
    val yellowLightSurfaceTint:          String = "#616200" // yellowLightPrimary
    val yellowLightInverseSurface:       String = "#31302b"
    val yellowLightInverseOnSurface:     String = "#f4f0e8"
    val yellowLightError:                String = "#BA1B1B"
    val yellowLightOnError:              String = "#FFFFFF"
    val yellowLightErrorContainer:       String = "#FFDAD6"
    val yellowLightOnErrorContainer:     String = "#410002"
    val yellowLightOutline:              String = "#797869"
    val yellowLightOutlineVariant:       String = "#79786950"

    val yellowDarkPrimary:              String = "#cbcc58" // yellowLightInversePrimary
    val yellowDarkOnPrimary:            String = "#323200"
    val yellowDarkPrimaryContainer:     String = "#494a00"
    val yellowDarkOnPrimaryContainer:   String = "#e8e971" // yellowLightPrimaryContainer
    val yellowDarkInversePrimary:       String = "#616200" // yellowLightPrimary
    val yellowDarkSecondary:            String = "#cac8a5"
    val yellowDarkOnSecondary:          String = "#323219"
    val yellowDarkSecondaryContainer:   String = "#48482d"
    val yellowDarkOnSecondaryContainer: String = "#e6e4bf" // yellowLightSecondaryContainer
    val yellowDarkTertiary:             String = "#00513e"
    val yellowDarkOnTertiary:           String = "#81f8d0"
    val yellowDarkTertiaryContainer:    String = "#254e40"
    val yellowDarkOnTertiaryContainer:  String = "#ffddaa" // yellowLightTertiaryContainer
    val yellowDarkBackground:           String = "#1c1c16"
    val yellowDarkOnBackground:         String = "#e5e2d9"
    val yellowDarkSurface:              String = "#1c1c16" // yellowDarkBackground
    val yellowDarkOnSurface:            String = "#e5e2d9" // yellowDarkOnBackground
    val yellowDarkSurfaceVariant:       String = "#48473a"
    val yellowDarkOnSurfaceVariant:     String = "#c9c7b6"
    val yellowDarkSurfaceTint:          String = "#cbcc58" // yellowDarkPrimary
    val yellowDarkInverseSurface:       String = "#31302b"
    val yellowDarkInverseOnSurface:     String = "#f4f0e8"
    val yellowDarkError:                String = "#ffb4a9"
    val yellowDarkOnError:              String = "#680003"
    val yellowDarkErrorContainer:       String = "#7D2B22"
    val yellowDarkOnErrorContainer:     String = "#FFDAD6" // yellowLightErrorContainer
    val yellowDarkOutline:              String = "#939182"
    val yellowDarkOutlineVariant:       String = "#93918250"
}